# Generated by Django 6.0.4 on 2026-04-15 18:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_starting_balance_100000'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaVantageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('retrieved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alpha_vantage_data', to='core.stock')),
            ],
            options={
                'ordering': ['-retrieved_at'],
            },
        ),
    ]
